### ISSUE TITLE
Kohana-modules should default to the lastest version of framework

### ISSUE THREAD

**Issue by d4rky-pl** [ahutchings/kohana-modules#40]
Currently when you visit kohana-modules.com, the default view is the list of all modules for all version of Kohana starting from 2.3 to 3.2. Most of the people don't see the distinction at first which creates unnecessary confusion over why modules aren't working.

I propose two things:
- First - set the default view from Any to 3.2, so modules for the most recent version of framework are being visible by entering the website
- Second - more visible linking to the per-version module (github's branches), because some modules don't use tags or use branching instead of tagging to support several versions of framework

**Comment by ahutchings** [comment]
Good suggestions - sorry about the delay in responding.

I have noticed that a large number of users are filtering by 3.2-only modules, so that seems like a sensible thing to do by default. For your second point, are you suggesting that module pages should have branch links, similar to the tag links that already exist? That certainly wouldn't hurt anything. I expect I'll get one or both of these done this week.

**Comment by d4rky-pl** [comment]
Most of the people keep at least two versions of their modules for both supported versions (3.1 and 3.2 in this case). Branches are much better for this task than tags ;)
